
##### RESOURCES #####
partition: 'shortq'
mem: '8000'
threads: 1


##### GENERAL #####
data: /path/to/data.csv # path to the input count-matrix as CSV file, formatted as feature x sample (rows x columns); unique features and samples are required.
annotation: /path/to/metadata.csv # path to the input sample annotation as CSV file, formatted as sample x metadata (rows x columns) 
result_path: /path/to/results/ # path to the output folder
project_name: MySeqData # name of the project/dataset

# path to the feature annotation as CSV file, required for RPKM quantification (feature length) and CQN normalization (feature length, covariate), otherwise empty ""
# formatted as feature x metadata (rows x columns)
feature_annotation: /path/to/feature_annotation.csv


##### SPLIT #####
# metadata column(s) by which the data should be split.
# to skip, leave empty i.e., []
split_by: ['organ', 'celltype']

##### FILTER #####
# parameters for the function edgeR:filterByExpr, default are in comments
# https://rdrr.io/bioc/edgeR/man/filterByExpr.html
filter_parameters:
    group: "condition" # "NULL"
    min.count: 10 # 10
    min.total.count: 15 # 15
    large.n: 10 # 10
    min.prop: 0.7 # 0.7

##### NORMALIZE #####
# method specific parameters, defaults are in the comments

### edgeR
# edgeR::CalcNormFactors -> https://rdrr.io/bioc/edgeR/man/calcNormFactors.html
# edgeR::cpm/rpkm -> https://rdrr.io/bioc/edgeR/man/cpm.html
# to skip leave method empty i.e., []
edgeR_parameters:
    method: ["TMM", "RLE", "none"] # "TMM","TMMwsp","RLE","upperquartile","none"
    refColumn: "NULL" # "NULL"; used by TMM
    logratioTrim: 0.3 # 0.3; used by TMM
    sumTrim: 0.05 # 0.05; used by TMM
    doWeighting: "TRUE" # "TRUE"; used by TMM
    Acutoff: -10000000000 # -10000000000; used by TMM
    p: 0.75 # 0.75; used by upperquartile
    quantification: "CPM" # Compute counts per million ("CPM") or reads per kilobase per million ("RPKM").
    log: "TRUE" # "TRUE"
    prior.count: 2 # default: 2
    gene.length: "length" # required for RPKM otherwise "", column name in feature annotation (specified above)

### CQN (requires feature annotation, configured above)
# cqn::cqn -> https://bioconductor.org/packages/release/bioc/html/cqn.html
# to skip leave x empty i.e., ""
cqn_parameters:
    x: "gc" # covariate, column name in feature annotation
    lengths: "length" # column name in feature annotation
    sizeFactors: "NULL" # "NULL" or column name in annotation
    tau: 0.5 # 0.5, only change if expert
    sqn: "TRUE" # "TRUE", only change if expert
    lengthMethod: "smooth" # "smooth" or "fixed"

### VOOM
# limma::voom -> https://rdrr.io/bioc/limma/man/voom.html
# to skip leave normalize.method empty i.e., ""
voom_parameters:
    calcNormFactors_method: "none" # "none"; options: any other supported method from edgeR::CalcNormFactors (parameters from above are used)
    normalize.method: "none" # "none"; options: "scale", "quantile", "cyclicloess"
    span: 0.5 # 0.5

##### INTEGRATE #####

### reComBat
# https://github.com/BorgwardtLab/reComBat
# requires log-normalized counts i.e., at least CPM
# to skip leave batch_column empty i.e., ""
reComBat_parameters:
    norm_methods: ["CQN", "TMM"] # list of normalization outputs to be integrated (required to be configured above) 
    batch_column: "experiment" # name of the batch column in annotation e.g., "batch"
    desired_categorical: ["organ","celltype","genotype"] # list of the column names of categorical variables of desired variation in annotation
    desired_numerical: [] # list of the column names of numerical variables of desired variation in annotation
    unwanted_categorical: [] # list of the column names of categorical variables of unwanted variation in annotation
    unwanted_numerical: [] # list of the column names of numerical variables of unwanted variation in annotation
    parametric: True # True
    model: 'linear' # 'linear', alternatives: ridge, lasso, elastic_net
    config: "" # "", Optional arguments for sklearn model, for 'linear' e.g., "{'fit_intercept':False,'copy_X':True,'n_jobs':1,'positive':False}"
    conv_criterion: 0.0001 # 0.0001
    max_iter: 1000 # 1000
    mean_only: False # False
    optimize_params: True # True
    reference_batch: "" # ""
    verbose: True # True

##### Highly Variable Features (HVF) #####
hvf_parameters:
    top_percentage: 10 # percentage of top features to select
    bins_n: 20 # number of bins to use for dispersion normalization
    
##### VISUALIZE #####
visualization_parameters:
    annotate: ["experiment", "celltype"] # up to 2 columns in annotation to be visualized in PCA-, density- and boxplots e.g., batch or treatment; can be empty i.e., []
    